const projects=[
{title:'BOTANICAL TEA',type:'package',label:'PACKAGE DESIGN · SAMPLE',desc:'보태니컬 일러스트를 담은 티 패키지 샘플',images:['assets/package-botanical-tea.png'],info:'AI 생성 비주얼을 활용한 가상 패키지디자인 샘플입니다. 세이지 그린과 크림 컬러, 식물 일러스트, 종이 질감으로 차 선물 세트의 차분한 인상을 표현했습니다. 실제 납품·출시 제품이 아닙니다.'},
{title:'첫 만남을 위한 선물',type:'popup',label:'PROMOTION · POPUP SAMPLE',desc:'신규 회원 웰컴 쿠폰 프로모션 샘플',images:['assets/popup-welcome.png'],info:'AI 생성 비주얼을 활용한 가상 팝업 디자인 샘플입니다. 라벤더 컬러와 입체 리본, 10% 타이포그래피로 혜택을 강조하고 하단 행동 버튼으로 시선을 연결했습니다. 할인 및 사용 조건은 디자인 예시이며 실제 이벤트가 아닙니다.'},
{title:'MOON BUDDY',type:'detail',label:'CHARACTER · COMMERCE',desc:'작은 캐릭터에 담은 밤의 위로',images:['assets/moon-buddy.png'],info:'신규 콘셉트 프로젝트 / 캐릭터 무드등 상세페이지. 포근한 캐릭터로 관심을 유도하고, 사용 장면 → 디테일 → 선물 → 이벤트 순으로 구매 흐름을 구성했습니다. AI 생성 비주얼을 활용한 디자인 시안이며 제품 사양·이벤트는 예시입니다.'},
{title:'PAW & GO',type:'detail',label:'PET LIFESTYLE · COMMERCE',desc:'함께 걷는 매일을 위한 산책 키트',images:['assets/paw-go.png'],info:'신규 콘셉트 프로젝트 / 반려견 산책 키트 상세페이지. 동물의 표정으로 감성적 관심을 만들고, 소재와 사용 장면으로 제품 이해를 돕습니다. 오렌지와 세이지의 대비로 정보를 구분했습니다. 제품 설명 및 혜택은 콘셉트 예시입니다.'},
{title:'DAILY BALANCE',type:'detail',label:'WELLNESS · DETAIL DESIGN',desc:'브랜드 분위기를 이어가는 제품 스토리',images:['output/health-detail-page-one/01-daily-balance-detail.png','output/health-detail-page-one/02-daily-balance-quality-routine.png'],info:'건강식품 상세페이지 디자인 시안. 숲속 히어로에서 밝은 제품 설명으로 전환하며 브랜드 톤을 연결한 작업입니다. 두 장을 순서대로 모두 확인할 수 있습니다. 가상 제품의 성분·품질 표현이며 실제 인증이나 검증된 제품 정보가 아닙니다.'},
...window.assetCatalog.map((item,i)=>({title:item.title,type:'banner',label:'CAMPAIGN · BANNER',desc:'메시지와 비주얼의 위계로 전달하는 프로모션',images:[item.path],info:'배너 디자인 작업. 주제에 맞는 색상과 타이포그래피, 제품 배치로 핵심 메시지를 빠르게 전달하도록 구성했습니다. 이미지 내 일정과 할인 혜택은 디자인 예시입니다.'}))];
const gallery=document.querySelector('#gallery'),viewer=document.querySelector('#viewer');let filter='all',limit=6;function render(){const list=projects.filter(p=>filter==='all'||p.type===filter);gallery.replaceChildren();list.slice(0,limit).forEach(p=>{const b=document.createElement('button');b.className='project';b.dataset.type=p.type;b.setAttribute('aria-label',p.title+' 전체 보기');b.innerHTML=`<div class="project-visual"><img loading="lazy" src="${encodeURI(p.images[0])}" alt="${p.title} 디자인"><span class="open-icon" aria-hidden="true">↗</span></div><div class="project-meta"><div><small>${p.label}</small><h3>${p.title}</h3><p>${p.desc}</p></div><span>VIEW ↗</span></div>`;b.onclick=()=>openProject(p);gallery.append(b)});document.querySelector('#more').hidden=list.length<=limit;const empty=document.querySelector('#empty');empty.hidden=list.length!==0;empty.textContent=filter==='package'?'패키지디자인 작업물 준비 중입니다.':'현재 등록된 작업물이 없습니다.'}
function openProject(p){document.querySelector('#viewer-title').textContent=p.title;document.querySelector('#viewer-info').textContent=p.info;document.querySelector('#original').href=p.images[0];const images=document.querySelector('#viewer-images');images.replaceChildren();p.images.forEach((src,i)=>{const img=new Image();img.src=src;img.alt=p.title+' 전체 디자인 '+(i+1);images.append(img)});viewer.showModal();viewer.scrollTop=0;document.body.classList.add('modal-open')}document.querySelector('#close').onclick=()=>viewer.close();viewer.addEventListener('close',()=>document.body.classList.remove('modal-open'));viewer.addEventListener('click',e=>{if(e.target===viewer){const r=viewer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)viewer.close()}});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;limit=6;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));render()});document.querySelector('#more').onclick=()=>{limit+=6;render()};render();
